DROP TABLE IF EXISTS AIRFLOW_DB.AIRFLOW.USERS;

CREATE TABLE IF NOT EXISTS AIRFLOW_DB.AIRFLOW.USERS (
  ID NUMERIC,
  DOCUMENT VARCHAR(255),
  NAME VARCHAR(255),
  BIRTHDAY VARCHAR(15),
  GENDER VARCHAR(20),
  EMAIL VARCHAR(255),
  PHONE VARCHAR(30)
);