DROP TABLE IF EXISTS AIRFLOW_DB.AIRFLOW.ORDERS;

CREATE TABLE AIRFLOW_DB.AIRFLOW.ORDERS (
  ID SERIAL PRIMARY KEY,
  USER_ID NUMERIC,
  ORDER_DATE VARCHAR(255),
  PRODUCT_ID NUMERIC,
  PRODUCT_NAME VARCHAR(255),
  CATEGORY VARCHAR(255),
  PRICE DECIMAL
);