DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS USERS (
  Id NUMERIC,
  Document VARCHAR(255),
  Name VARCHAR(255),
  BirthDay VARCHAR(15),
  Gender VARCHAR(20),
  Email VARCHAR(255),
  Phone VARCHAR(30)
);